import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Person, prettyPrintPerson } from "monorepo-test-utils";
import { Button } from 'monorepo-test-utils-2';

const Home: NextPage = () => {
    const rajat: Person = {
        name: "Rajat",
        age: 34
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Vercel Monorepo Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{prettyPrintPerson(rajat)}</p>
        <Button caption="Hehe"></Button>
      </main>

      <footer className={styles.footer}>
          <p>By Rajat</p>
      </footer>
    </div>
  )
}

export default Home
